name: test
on: [push]
jobs:
  cypress-run:
	runs-on: ubuntu-latest
	name: e2e on Chrome
	steps:
	  - uses: actions/checkout@v2
	  - uses: cypress-io/github-action@v2
		with:
		  install-command: yarn install
		  browser: chrome
		  repository: steveblue/web-components-exercises
		  ref: refs/heads/master
		  token: ${{ secrets.GITHUB_TOKEN }}
		  persist-credentials: false
		  build: yarn build
		  start: yarn start
		  wait-on: http://localhost:6006